### ISSUE TITLE
[Feature request] Clickable CloudFormation types with links to documentation

### ISSUE THREAD

**Issue by PatrykMilewski** [theodo/serverless-ide-plugins#5]
Hello!

Thank you for making this plugin! I was waiting for it for a long time!

I'm missing one simple feature. I would like to be able to click on type definition, which would point to CloudFormation documentation for it.

Example:
```
MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "my-queue"
        VisibilityTimeout: 180
```
The link should be working for `Type: AWS::SQS::Queue` part.

It would be a cool feature, since I'm usually doing it manually and it's a little bit slow. The best solution would be to open a new browser tab/window, but if it's complicated to implement, displaying a link to copy would be also fine.
